---
# tasks file for multipath-iscsi

- name: Install required packages
  yum:
    name: "{{ multipath_iscsi_packages }}"
    state: present
  tags:
    - install

- name: "Add multipath config"
  template:
    src: multipath.conf.j2
    dest: /etc/multipath.conf
    owner: root
    group: root
    mode: 0644
  notify: restart multipathd
  tags:
    - config


- name: Loading multipath Kernel Module
  modprobe:
    name: dm-multipath
    state: present
  tags:
    - install

- name: "Add iscsid config"
  template:
    src: iscsid.conf.j2
    dest: /etc/iscsi/iscsid.conf
    owner: root
    group: root
    mode: 0600
  notify: restart iscsid
  tags:
    - config

- name: Configuring initiator.iscsi
  template:
    src: "initiatorname.iscsi.j2"
    dest: /etc/iscsi/initiatorname.iscsi
    mode: 0644
    owner: root
    group: root
  notify: restart iscsid
  tags:
    - config

- name: Ensure services
  service:
    name: '{{ item }}'
    state: started
    enabled: true
  with_items:
    - multipathd
    - iscsid

- name: copy check_multipath
  copy:
    src: check_multipath
    dest: /usr/lib64/nagios/plugins/check_multipath
    owner: root
    group: root
    mode: 0755
  tags:
    - nrpe
    - plugin
    - install

- name: copy nrpe check definition
  template:
    src: check_multipath.cfg.j2
    dest: /etc/nrpe.d/check_multipath.cfg
    owner: nrpe
    group: nrpe
    mode: 0644
  notify: restart nrpe
  tags:
    - nrpe
    - config
    - plugin

- name: Allow nrpe to sudo multipath
  template:
    src: 50-nrpe-check-multipath.j2
    dest: /etc/sudoers.d/50-nrpe-check-multipath
    owner: root
    group: root
    mode: 0640
    validate: '/usr/sbin/visudo -cf %s'
  tags:
    - nrpe
    - sudo
