---
# tasks file for multipath-iscsi

- name: Install required packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - iscsi-initiator-utils
    - device-mapper-multipath
    - lsof
  tags:
    - install

- name: "Add multipath config"
  template:
    src: multipath.conf.j2
    dest: /etc/multipath.conf
    owner: root
    group: root
    mode: 0644
  notify: restart multipathd
  tags:
    - config


- name: Loading multipath Kernel Module
  modprobe:
    name: dm-multipath
    state: present
  tags:
    - install

- name: "Add iscsid config"
  template:
    src: iscsid.conf.j2
    dest: /etc/iscsi/iscsid.conf
    owner: root
    group: root
    mode: 0600
  notify: restart iscsid
  tags:
    - config

- name: Configuring initiator.iscsi
  template:
    src: "initiatorname.iscsi.j2"
    dest: /etc/iscsi/initiatorname.iscsi
    mode: 0644
    owner: root
    group: root
  notify: restart iscsid
  tags:
    - config

- name: Ensure services
  service:
    name: '{{ item }}'
    state: started
    enabled: true
  with_items:
    - multipathd
    - iscsid

